# Generated by Django 5.2.7 on 2025-10-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "historico_medico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Histórico Médico"
                    ),
                ),
                (
                    "alergias",
                    models.TextField(blank=True, null=True, verbose_name="Alergias"),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacientes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médico Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="PDFPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="pacientes/pdfs/", verbose_name="Arquivo PDF"
                    ),
                ),
                (
                    "nome_documento",
                    models.CharField(max_length=255, verbose_name="Nome do Documento"),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdfs",
                        to="core.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento PDF",
                "verbose_name_plural": "Documentos PDFs",
            },
        ),
        migrations.CreateModel(
            name="PhotoPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        upload_to="pacientes/fotos/", verbose_name="Foto"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="core.patient",
                        verbose_name="paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do Paciente",
                "verbose_name_plural": "Fotos do Paciente",
            },
        ),
    ]
